biblio/src/Entity/Loan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LoanRepository")
 */
class Loan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startdate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $enddate;


    /**
     * @var \DateTime
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $restitutionprev;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="loans")
     * @Assert\NotBlank(message="Adhérent obligatoire !")
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="loans")
     *
     */
    private $Book;

    public function __construct()
    {
        $this->startdate = new \DateTime('NOW');
        $today =  new \DateTime('NOW');
        $delai = new \DateInterval('P1M');
//
       $this->restitutionprev = $today->add($delai);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartdate(): ?\DateTimeInterface
    {
        return $this->startdate;
    }

    public function setStartdate(\DateTimeInterface $startdate): self
    {
        $this->startdate = $startdate;

        return $this;
    }

    public function getEnddate(): ?\DateTimeInterface
    {
        return $this->enddate;
    }

    public function setEnddate(?\DateTimeInterface $enddate): self
    {
        $this->enddate = $enddate;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->Book;
    }

    public function setBook(?Book $Book): self
    {
        $this->Book = $Book;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getRestitutionprev(): \DateTime
    {
        return $this->restitutionprev;
    }

    /**
     * @param \DateTime $restitutionprev
     * @return Loan
     */
    public function setRestitutionprev(\DateTime $restitutionprev): Loan
    {
        $this->restitutionprev = $restitutionprev;
        return $this;
    }

}

biblio/src/Form/LoanType.php
<?php

namespace App\Form;

use App\Entity\Book;
use App\Entity\Loan;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LoanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder


            ->add('User',EntityType::class,[
                'class' => User::class,
                'label' => 'Adhérents :',
                'placeholder' => 'Séléctionnez un adhérent'

            ])
//            ->add('Book',EntityType::class,[
//                'class' => Book::class,
//                'label' => 'Livres : ',
//                'placeholder' => 'Séléctionnez un Livre :'
//            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Loan::class,
        ]);
    }
}

biblio/src/Controller/LoanController.php
<?php

namespace App\Controller;

use App\Entity\Loan;
use App\Form\ContactUserType;
use App\Form\LoanType;
use App\Repository\BookRepository;
use App\Repository\LoanRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\DataCollector\DumpDataCollector;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * @IsGranted("ROLE_USER")
 * Class LoanController
 * @package App\Controller
 */
class LoanController extends AbstractController
{
    /**
     * @Route("/loan", name="loan")
     * @param LoanRepository $loanRepository
     * @return Response
     * @throws \Exception
     */
    public function index(LoanRepository $loanRepository)
    {
            $date = new \DateTime('NOW');

           // $dateToday = $date->format('d/m/Y');



            $listEmprunts =  $loanRepository->findBy([],[
                'startdate' => 'ASC'
            ]);


        return $this->render('loan/index.html.twig', [
            'list' => $listEmprunts,
            'date' => $date
        ]);
    }

    /**
     * @Route("/editLoan", name="editloan")
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param BookRepository $bookRepository
     * @return Response
     * @throws \Exception
     */
    public function editLoan(Request $request,EntityManagerInterface $manager,BookRepository $bookRepository)
    {


        $emprunt = new Loan();

        $date = new \DateTime('NOW');
        $empruntsList = $this->createForm(LoanType::class,$emprunt);


        $bookDispos = $bookRepository->findBy([
            'isRent' => false

        ],[]);



        $empruntsList->handleRequest($request);

        if ($empruntsList->isSubmitted()) {

            if ($empruntsList->isValid()) {

                $bookId = $request->request->get('choicebook');

                if (!empty($bookId)) {

                    $bookChoice = $bookRepository->find($bookId);
                    $emprunt->setBook($bookChoice);

                    $bookChoice->setIsRent(true);
                    $titleBook = $bookChoice->getTitle();
                    $userRent = $emprunt->getUser();
                    $manager->persist($emprunt);
                    $manager->flush();

                  $this->addFlash('success',"<p class='text-center'> Le livre <strong>$titleBook</strong> à été emprunté par <strong>$userRent</strong></p>");
                    return $this->redirectToRoute('loan');


                }

            } else {
                $this->addFlash('error',"<p class='text-center'>Le formulaire contient des erreurs !</p>");
            }
        } else {
            $test = null;
            $isRent = null;
        }

        return $this->render('loan/edit_loan.html.twig',[
            'form' =>$empruntsList->createView(),
            'date' => $date,

            'listBook' => $bookDispos
        ]);
    }

    /**
     * @Route("/restitution/{id}",name="restitute")
     * @param Loan $loan
     * @param BookRepository $bookRepository
     * @param EntityManagerInterface $manager
     * @return RedirectResponse
     */
    public function getRestitution(Loan $loan,BookRepository $bookRepository,EntityManagerInterface $manager)
    {
        $restituedBookId = $loan->getBook()->getId();
        $bookAvailable =$bookRepository->find($restituedBookId);
        $bookTitle = $bookAvailable->getTitle();
        $bookAuthor = $bookAvailable->getAuthor();
        $firstNameUserRent = $loan->getUser()->getFirstname();
        $lastNameUserRent = $loan->getUser()->getLastname();

        $bookAvailable->setIsRent(false);

        $manager->remove($loan);
        $manager->flush();

        if (is_null($loan->getId())) {
            $this->addFlash('success',"<p class='text-center'>Le livre <strong>$bookTitle</strong> de <strong>$bookAuthor</strong> a été restitué par <strong> $firstNameUserRent $lastNameUserRent</strong></p>");

        } else {
            $this->addFlash('error',"<p class='text-center'><strong>Une erreur est survenue lors de la restitution</strong></p>");
        }
        return $this->redirectToRoute('loan');

    }

    /**
     * @Route("/contactUser/{id}",name="contactuser")
     * @param Request $request
     * @param Loan $loan
     * @param \Swift_Mailer $mailer
     * @return Response
     */
    public function sendMailToAdherant(Request $request,Loan $loan,\Swift_Mailer $mailer)
    {
        $firstnameUser = $loan->getUser()->getFirstname();
        $lastnameUser = $loan->getUser()->getLastname();
        $mailUser = $loan->getUser()->getEmail();
        $bookTitle = $loan->getBook()->getTitle();
        $bookAuthor = $loan->getBook()->getAuthor();
        $prevDateRestitution = $loan->getRestitutionprev()->format('d/m/Y');
        $loanDate = $loan->getStartdate()->format('d/m/Y');

        $subjectMail = "RETARD DE RESTITUTION DE LIVRE A LA BIBLIOTHEQUE";
        $contentMail = "A l'attention de $firstnameUser $lastnameUser,\n";
        $contentMail .= "Le livre $bookTitle de $bookAuthor";
        $contentMail .= " que vous avez emprunté le $loanDate est toujours en votre possession.\n";
        $contentMail .= "Ce dernier aurait dû être réstitué au plus tard le $prevDateRestitution !\n ";
        $contentMail .= "Merci de le rapporter immédiatement, sous peine de poursuites.\n";
        $contentMail .= "Cordialement,\n ";
        $contentMail .= "La direction.";

        $form = $this->createForm(ContactUserType::class);
        $form->get('email')->setData($mailUser);
        $form->get('subject')->setData($subjectMail);
        $form->get('content')->setData($contentMail);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            if ($form->isValid()) {
                $data = $form->getData();
                $expeditor = $this->getParameter('contact_email');

                $mail = $mailer->createMessage();
                $mailBody = $this->renderView('loan/contact_body.html.twig',[
                    'datas' => $data
                ]);

                $mail->setSubject($subjectMail)
                     ->setFrom($expeditor)
                     ->setTo($mailUser)
                     ->setBody($mailBody,'text/html')
                     ->setReplyTo($expeditor)
                ;

                $mailer->send($mail);
                $this->addFlash('success',"<p class='text-center'>Le message de relance a bien été envoyé à $mailUser</p>");
                    return $this->render('loan/view_message_sent.html.twig',[
                        'datas' => $data
                    ]);


            } else {
                $this->addFlash('error',"Le formulaire contient des erreurs");
            }
        }


        return $this->render('loan/contact_user.html.twig',[
            'form' => $form->createView()
        ]);
    }
}

biblio/templates/loan/contact_body.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>

<h3>Nouveau message de relance envoyé à : {{ datas.email }}</h3>
<p>Sujet : <strong>{{ datas.subject }}</strong></p>
<p> Message : <br><strong>{{ datas.content }}</strong></p>
</html>

biblio/templates/loan/contact_user.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Formulaire de relance
{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-3">

            <div class="card text-center">
                {{ form_start(form) }}
                <div class="card-header">
                FORMULAIRE DE RELANCE
                </div>
                <div class="card-body">
                {{ form_row(form.email) }}
                    {{ form_row(form.subject) }}
                    {{ form_row(form.content) }}
                </div>
                <div class="card-footer">
                <button type="submit" class="btn btn-dark">Envoyer</button>
                    <a href="{{ path('loan') }}" class="btn btn-outline-dark">Retour</a>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

biblio/templates/loan/edit_loan.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Ajouter un emprunt
{% endblock %}

{% block body %}
    <div class="text-center"><h2>Ajouter un emprunt</h2></div>
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-5 mt-3">
            <div class="card">
                <div class="card-body">
            {{ form_start(form) }}

            {{ form_row(form.User) }}
                    <label for="lstbook">Liste Livres disponibles au {{ date|date('d/m/Y') }}</label>
                   <select class="form-control" name="choicebook" id="lstbook">
                        {% for book in listBook %}

                            <option value="{{ book.id }}">{{ book.title }} DE {{ book.author }}</option>
                       {% endfor %}

                   </select>
                    <div class="text-right">
                        <button type="submit" class="btn btn-outline-primary mt-3">Emprunt</button>
                        <a href="{{ path('loan') }}" class="btn btn-dark mt-3">Retour</a>
                    </div>
            {{ form_end(form) }}
                </div>
            </div>
            <br>

        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

biblio/templates/loan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunts{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-10 mt-3">
            <div class="text-center">
                <h1>Gestion des emprunts</h1>
                <a href="{{ path('editloan') }}" class="btn btn-outline-dark">Ajouter</a>
                <div class="table-responsive mt-3 mb-3">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Adhérent</th>
                                <th scope="col">Livre</th>
                                <th scope="col">Date d'emprunt</th>
                                <th scope="col">Date Réstitution prévue</th>
                                <th scope="col">Statut</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for emprunt in list %}
                            <tr>
                                <th scope="row">
                                    {{ emprunt.id }}
                                </th>
                                <td align="center">
                                    {{ emprunt.user }}
                                </td>
                                <td align="center">
                                    {{ emprunt.book }}
                                </td>
                                <td align="center">
                                    {{ emprunt.startdate|date('d/m/Y') }}
                                </td>
                                <td align="center">

                                        {{ emprunt.restitutionprev|date('d/m/Y') }}


                                </td>
                                <td align="center">
                                    {% if date > emprunt.restitutionprev %}

                                        <img src="{{ asset('images/red.png') }}" width="25px" height="25px"><br>
                                        <a href="{{ path('contactuser',{ 'id' : emprunt.id }) }}" class="btn btn-warning mt-3">Mail</a>
                                    {% else %}
                                        <img src="{{ asset('images/green.png') }}" width="25px" height="25px">
                                    {% endif %}
                                </td>
                                <td align="center">
                                    <a href="{{ path('restitute',{ 'id' : emprunt.id }) }}" class="btn btn-success">Restitution</a>
                                </td>
                            </tr>
                                {% else %}
                            <tr>
                                <td colspan="7" align="center" class="bg-info">
                                  <strong>Aucun emprunt actuellement</strong>
                                </td>

                            </tr>
                        </tbody>
                        <tr>
                            <td colspan="7">
                            <pre>
                                {{ dump(emprunt.restitutionprev|date('d/m/Y')) }}
                            </pre>
                            </td>
                        </tr>
                            {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock %}

biblio/templates/loan/view_message_sent.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Message envoyé
{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-3">
            <div class="card text-center">
                <div class="card-header">
                    MESSAGE DE RELANCE ENVOYE A : {{ datas.email }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Sujet : {{ datas.subject }}</h5>
                    <p class="card-text">
                        {{ datas.content|nl2br }}
                    </p>
                </div>
                <div class="card-footer">
                    <a href="{{ path('loan') }}" class="btn btn-dark">Retour</a>
                </div>
            </div>

        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}