biblio/src/Entity/Loan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LoanRepository")
 */
class Loan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startdate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $enddate;


    /**
     * @var \DateTime
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $restitutionprev;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="loans")
     * @Assert\NotBlank(message="Adhérent obligatoire !")
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="loans")
     *
     */
    private $Book;

    public function __construct()
    {
        $this->startdate = new \DateTime('NOW');
        $today =  new \DateTime('NOW');
        $delai = new \DateInterval('P1M');
//
       $this->restitutionprev = $today->add($delai);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartdate(): ?\DateTimeInterface
    {
        return $this->startdate;
    }

    public function setStartdate(\DateTimeInterface $startdate): self
    {
        $this->startdate = $startdate;

        return $this;
    }

    public function getEnddate(): ?\DateTimeInterface
    {
        return $this->enddate;
    }

    public function setEnddate(?\DateTimeInterface $enddate): self
    {
        $this->enddate = $enddate;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->Book;
    }

    public function setBook(?Book $Book): self
    {
        $this->Book = $Book;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getRestitutionprev(): \DateTime
    {
        return $this->restitutionprev;
    }

    /**
     * @param \DateTime $restitutionprev
     * @return Loan
     */
    public function setRestitutionprev(\DateTime $restitutionprev): Loan
    {
        $this->restitutionprev = $restitutionprev;
        return $this;
    }

}

biblio/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="Le nom de l'adhérent est obligatoire !")
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="Le prénom de l'adhérent est obligatoire !")
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Email(message="Email invalide")
     * @Assert\NotBlank(message="Le mail est obligatoire ! ")
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Loan", mappedBy="User")
     */
    private $loans;

    public function __construct()
    {
        $this->loans = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->firstname. ' '.$this->lastname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Loan[]
     */
    public function getLoans(): Collection
    {
        return $this->loans;
    }

    public function addLoan(Loan $loan): self
    {
        if (!$this->loans->contains($loan)) {
            $this->loans[] = $loan;
            $loan->setUser($this);
        }

        return $this;
    }

    public function removeLoan(Loan $loan): self
    {
        if ($this->loans->contains($loan)) {
            $this->loans->removeElement($loan);
            // set the owning side to null (unless already changed)
            if ($loan->getUser() === $this) {
                $loan->setUser(null);
            }
        }

        return $this;
    }
}

biblio/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname',TextType::class,[
                'required' => true,
                'label' => 'Nom'
            ])
            ->add('firstname',TextType::class,[
                'required' => true,
                'label' => 'Prénom'
            ])
            ->add('email',EmailType::class,[
                'required' => true,
                'label' =>  'Email'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

biblio/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Loan;
use App\Entity\User;
use App\Form\SearchUserType;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;



/**
 * @IsGranted("ROLE_USER")
 * Class UserController
 * @package App\Controller
 */
class UserController extends AbstractController
{
    /**
     * @Route("/user/{page}", requirements={"page" : "\d+"},defaults={"page" : 1},name="user")
     * @param Request $request
     * @param UserRepository $userRepository
     * @return Response
     * @param $page
     */
    public function index(Request $request,UserRepository $userRepository,$page)
    {
        $formSearch = $this->createForm(SearchUserType::class);
        $formSearch->handleRequest($request);

        $listUsers = $userRepository->searchUser((array)($formSearch->getData()));

        $adapter = new DoctrineORMAdapter($listUsers);
        $pager = new Pagerfanta($adapter);
        $pager->setMaxPerPage($this->getParameter('nb_user_per_page'));
        $pager->setCurrentPage((int)$page);

        return $this->render('user/index.html.twig', [
            'pager' => $pager,
            'page' => $page,
            'search' => $formSearch->createView()
        ]);
    }

    /**
     * @Route("/datatableList",name="listdatatable")
     * @param Request $request
     * @param UserRepository $userRepository
     * @return Response
     */
    public function indexDataTable(Request $request,UserRepository $userRepository)
    {
        $formSearch = $this->createForm(SearchUserType::class);
        $formSearch->handleRequest($request);

        $listUsers = $userRepository->searchUser((array)($formSearch->getData()));

       return $this->render('user/list_data_table.html.twig',[
            'list' => $listUsers
       ]);
        }

    /**
     * @Route("/editUser/{id}",name="edituser",defaults={"id": null},requirements={"id" : "\d+"})
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param $id
     * @return Response
     */
    public function editUser(Request $request, EntityManagerInterface $manager,$id)
    {

        if (is_null($id)) {
            $user = new User();
            $type = "Ajouter";
        } else {
            $user = $manager->find(User::class,$id);
            $type ="Modifier";

            if (is_null($user)) {
                throw new NotFoundHttpException();
            }

        }


        $form = $this->createForm(UserType::class,$user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            if ($form->isValid()) {
                $firstNameUser = $user->getFirstname();
                $lastNameUser = $user->getLastname();

                $manager->persist($user);
                $manager->flush();

                $this->addFlash('success',"<p class='text-center'>Le nouvel adhérent <strong>$firstNameUser $lastNameUser</strong> est enregistré.</p>");

                return $this->redirectToRoute('user');
            }
        }


        return $this->render('user/edit_user.html.twig',[
            'form' => $form->createView(),

            'type' => $type
        ]);
    }

    /**
     * @Route("/deleteUser/{id}",name="deleteuser")
     * @param User $user
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function deleteUser(User $user,EntityManagerInterface $manager)
    {

        $lastNameUser = $user->getLastname();
        $firstNameUser = $user->getFirstname();

        $loans = $user->getLoans();
        $nbLoans = count($loans);

        if ( $nbLoans > 0 ) {
           $this->addFlash('warning',"<p class='text-center'>Suppression impossible, <strong>$firstNameUser $lastNameUser</strong> à un ou des emprunt(s) en cours </p>");

           return $this->redirectToRoute('listloans',['id' => $user->getId()]);
        } else {
            $manager->remove($user);
            $manager->flush();
            $this->addFlash('success',"<p class='text-center'><strong>$firstNameUser $lastNameUser</strong> n'est plus adhérent.</p>");

            return $this->redirectToRoute('user');
        }


    }

    /**
     * @Route("/listLoans/{id}",name="listloans")
     * @param User $user
     * @return Response
     */
    public function listLoansForUser(User $user)
    {

        $loans = $user->getLoans();

        return $this->render('user/list_loan.html.twig',[
            'loans' => $loans,
            'user' => $user
        ]);
    }

}

biblio/templates/user/edit_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Edition Adhérent
{% endblock %}

{% block body %}
<div class="text-center"><h2>{{ type }} un adhérent</h2></div>
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-5 mt-3">
            <div class="card">
                <div class="card-body">
                    {{ form_start(form) }}
                    {{ form_row(form.lastname) }}
                    {{ form_row(form.firstname) }}
                    {{ form_row(form.email) }}
                    <div class="text-right">
                        <button type="submit" class="btn btn-outline-success">Valider</button>
                        <a href="{{ path('user') }}" class="btn btn-outline-dark">Retour</a>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

biblio/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adhérents{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-10 mt-3">
            <div class="text-center">
                <h2>Liste des adhérents</h2>

            </div>
            <div class="card text-center">
                {{ form_start(search) }}
                <div class="card-header">
                    RECHERCHER UN ADHERENT
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-6">
                        {{ form_row(search.lastname) }}
                        </div>
                        <div class="col-md-6">
                        {{ form_row(search.firstname) }}
                        </div>

                    </div>
                </div>
                <div class="card-footer">
                    <input type="hidden" name="page" value="{{ page }}"/>
                    <button type="submit" class="btn btn-dark">Rechercher</button>
                    <a href="{{ path('edituser') }}" class="btn btn-primary">Ajouter</a>
                </div>
                {{ form_end(search) }}
            </div>
            <div class="table-responsive mt-3">
                <table class="table table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="text-center">ID</th>
                            <th scope="col" class="text-center">NOM</th>
                            <th scope="col" class="text-center">PRENOM</th>
                            <th scope="col" class="text-center">EMAIL</th>
                            <th scope="col" class="text-center">EMPRUNTS</th>
                            <th scope="col" class="text-center">ACTION</th>
                        </tr>
                        <tr>
                            <td colspan="6" class="text-center">
                                <a href="{{ path('listdatatable') }}" class="btn btn-info">
                                    DataTable Vue Rapide
                                </a>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for user in pager.currentPageResults %}
                        <tr>
                            <th scope="row">
                                {{ user.id }}
                            </th>
                            <td align="center">
                                {{ user.lastname }}
                            </td>
                            <td align="center">
                                {{ user.firstname }}
                            </td>
                            <td align="center">
                                {{ user.email }}
                            </td>
                            <td align="center">
                                {% if user.loans.count > 0 %}
                                    <a href="{{ path('listloans',{ 'id' : user.id }) }}" class="btn btn-info">Liste</a>
                                    {% else %}
                                        <strong>Aucun</strong>
                                {% endif %}
                            </td>
                            <td align="center">
                                <a href="{{ path('edituser',{'id' : user.id }) }}" class="btn btn-success">Modifier</a>
                                <a href="{{ path('deleteuser',{'id' : user.id }) }}" class="btn btn-danger">Supprimer</a>
                            </td>
                        </tr>

                        {% else %}
                        <tr>
                            <td colspan="6" align="center" class="bg-info">
                                <strong>Pas d'adhérent actuellement</strong>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-center">

                    {{ pagerfanta(pager,'twitter_bootstrap4_translated') }}
                </div>
            </div>

        </div>
        <div class="col"></div>
    </div>
</div>



{% endblock %}

biblio/templates/user/list_data_table.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-5">
           <table id="table_id" class="table table-bordered table-dark">
               <thead>
                 <tr>
                     <th>ID</th>
                     <th>NOM</th>
                     <th>PRENOM</th>
                     <th>MAIL</th>
                 </tr>
               </thead>
               <tbody>
               {% for user in list %}
                    <tr class="bg-primary">
                        <td>
                            {{ user.id }}
                        </td>
                        <td>
                            {{ user.lastname }}
                        </td>
                        <td>
                            {{ user.firstname }}
                        </td>
                        <td>
                            {{ user.email }}
                        </td>
                    </tr>

               {% endfor %}
               </tbody>
           </table>


        </div>
        <div class="col"></div>

    </div>
</div>




{% endblock %}


{% block javascripts %}

{{ parent() }}
<script type="application/javascript">


    $(document).ready( function () {
    $('#table_id').DataTable();
    } );
</script>
{% endblock %}

biblio/templates/user/list_loan.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Liste emprunts
{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-7 mt-5 mb-3">
            <div class="card text-center mb-3">
                <div class="card-header">
                    {{ loans|length }} EMPRUNT(S) EN COURS
                    <br>ADHERENT : <strong>{{ user.firstname }} {{ user.lastname }}</strong>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">TITRE DU LIVRE</th>
                                    <th scope="col">AUTHEUR</th>
                                    <th scope="col">DATE SORTIE</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for loan in loans %}
                                <tr>
                                  <th scope="row">{{ loan.book.id }}</th>
                                    <td>{{ loan.book.title }}</td>
                                    <td>{{ loan.book.author }}</td>
                                    <td>{{ loan.startdate|date('d/m/Y') }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="card-footer text-center">
                    <a href="{{ path('user') }}" class="btn btn-outline-dark">Retour</a>
                </div>
            </div>

        </div>
        <div class="col"></div>

    </div>
</div>


{% endblock %}